Updated role tests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,10 +6,13 @@ variables:
   lxc: 'job$CI_JOB_ID'
 
 stages:
-  - test
+  - BackendDB_mairiadb
+  - BackendDB_mysql
+  - BackendDB_psql
+  - WebServer_Nginx
 
-UbuntuXenial:
-  stage: test
+UbuntuXenialMariadb:
+  stage: BackendDB_mairiadb
   before_script:
   # Create ansible.cfg with correct roles_path
   - printf '[defaults]\nroles_path=../' > ansible.cfg
@@ -27,12 +30,12 @@ UbuntuXenial:
 
     provisioning:
       - type: ansible
-        playbook: tests/UbuntuXenial.yml
+        playbook: tests/nextcloud_mariadb.yml
     """ > .lxdock.yml
   
   script:
     # Basic role syntax check
-    - ansible-playbook tests/UbuntuXenial.yml -i tests/inventory --syntax-check
+    - ansible-playbook tests/nextcloud_mariadb.yml -i tests/inventory --syntax-check
 
     # Deploy lxdock project and run the role/playbook
     - lxdock up
@@ -45,14 +48,19 @@ UbuntuXenial:
       || (echo 'Idempotence test: fail' && exit 1)
 
     # Check for role is done
+    - lxdock shell $lxc -c nestat -ntulp
+    # - lxdock shell $lxc -c nestat -ntulp | grep -q apache2
+    # - lxdock shell $lxc -c nestat -ntulp | grep -q mariadb
+    # - lxdock shell $lxc -c nestat -ntulp | grep -q redis
+
     # test login pages
     - lxdock shell $lxc -c curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"
   
   after_script:
   - lxdock destroy -f
 
-UbuntuTrusty:
-  stage: test
+UbuntuXenialMysql:
+  stage: BackendDB_mysql
   before_script:
   # Create ansible.cfg with correct roles_path
   - printf '[defaults]\nroles_path=../' > ansible.cfg
@@ -64,20 +72,18 @@ UbuntuTrusty:
 
     containers:
       - name: $lxc
-        image: ubuntu/trusty
+        image: ubuntu/xenial
         hostnames:
           - $lxc
 
     provisioning:
       - type: ansible
-        playbook: tests/UbuntuTrusty.yml
+        playbook: tests/nextcloud_mysql.yml
     """ > .lxdock.yml
-
-  - cat .lxdock.yml
   
   script:
     # Basic role syntax check
-    - ansible-playbook tests/UbuntuTrusty.yml -i tests/inventory --syntax-check
+    - ansible-playbook tests/nextcloud_mysql.yml -i tests/inventory --syntax-check
 
     # Deploy lxdock project and run the role/playbook
     - lxdock up
@@ -90,6 +96,279 @@ UbuntuTrusty:
       || (echo 'Idempotence test: fail' && exit 1)
 
     # Check for role is done
+    - lxdock shell $lxc -c nestat -ntulp
+    # - lxdock shell $lxc -c nestat -ntulp | grep -q apache2
+    # - lxdock shell $lxc -c nestat -ntulp | grep -q mysql
+    # - lxdock shell $lxc -c nestat -ntulp | grep -q redis
+
+    # test login pages
+    - lxdock shell $lxc -c curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"
+  
+  after_script:
+  - lxdock destroy -f
+
+UbuntuXenialPsql:
+  stage: BackendDB_psql
+  before_script:
+  # Create ansible.cfg with correct roles_path
+  - printf '[defaults]\nroles_path=../' > ansible.cfg
+
+  # Create .lxdock.yml
+  - |
+    echo """
+    name: $project
+
+    containers:
+      - name: $lxc
+        image: ubuntu/xenial
+        hostnames:
+          - $lxc
+
+    provisioning:
+      - type: ansible
+        playbook: tests/nextcloud_psql.yml
+    """ > .lxdock.yml
+  
+  script:
+    # Basic role syntax check
+    - ansible-playbook tests/nextcloud_psql.yml -i tests/inventory --syntax-check
+
+    # Deploy lxdock project and run the role/playbook
+    - lxdock up
+
+    # Run the role/playbook again, checking to make sure it's idempotent
+    - >
+      lxdock provision
+      | grep -q 'changed=0.*failed=0'
+      && (echo 'Idempotence test: pass' && exit 0)
+      || (echo 'Idempotence test: fail' && exit 1)
+
+    # Check for role is done
+    - lxdock shell $lxc -c nestat -ntulp
+    # - lxdock shell $lxc -c nestat -ntulp | grep -q apache2
+    # - lxdock shell $lxc -c nestat -ntulp | grep -q psql
+    # - lxdock shell $lxc -c nestat -ntulp | grep -q redis
+
+    # test login pages
+    - lxdock shell $lxc -c curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"
+  
+  after_script:
+  - lxdock destroy -f
+
+UbuntuXenial:
+  stage: WebServer_Nginx
+  before_script:
+  # Create ansible.cfg with correct roles_path
+  - printf '[defaults]\nroles_path=../' > ansible.cfg
+
+  # Create .lxdock.yml
+  - |
+    echo """
+    name: $project
+
+    containers:
+      - name: $lxc
+        image: ubuntu/xenial
+        hostnames:
+          - $lxc
+
+    provisioning:
+      - type: ansible
+        playbook: tests/nextcloud_nginx.yml
+    """ > .lxdock.yml
+  
+  script:
+    # Basic role syntax check
+    - ansible-playbook tests/nextcloud_nginx.yml -i tests/inventory --syntax-check
+
+    # Deploy lxdock project and run the role/playbook
+    - lxdock up
+
+    # Run the role/playbook again, checking to make sure it's idempotent
+    - >
+      lxdock provision
+      | grep -q 'changed=0.*failed=0'
+      && (echo 'Idempotence test: pass' && exit 0)
+      || (echo 'Idempotence test: fail' && exit 1)
+
+    # Check for role is done
+    - lxdock shell $lxc -c nestat -ntulp
+    # test login pages
+    - lxdock shell $lxc -c curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"
+  
+  after_script:
+  - lxdock destroy -f
+
+UbuntuTrustyMariadb:
+  stage: BackendDB_mairiadb
+  before_script:
+  # Create ansible.cfg with correct roles_path
+  - printf '[defaults]\nroles_path=../' > ansible.cfg
+
+  # Create .lxdock.yml
+  - |
+    echo """
+    name: $project
+
+    containers:
+      - name: $lxc
+        image: ubuntu/xenial
+        hostnames:
+          - $lxc
+
+    provisioning:
+      - type: ansible
+        playbook: tests/nextcloud10_mariadb.yml
+    """ > .lxdock.yml
+  
+  script:
+    # Basic role syntax check
+    - ansible-playbook tests/nextcloud10_mariadb.yml -i tests/inventory --syntax-check
+
+    # Deploy lxdock project and run the role/playbook
+    - lxdock up
+
+    # Run the role/playbook again, checking to make sure it's idempotent
+    - >
+      lxdock provision
+      | grep -q 'changed=0.*failed=0'
+      && (echo 'Idempotence test: pass' && exit 0)
+      || (echo 'Idempotence test: fail' && exit 1)
+
+    # Check for role is done
+    - lxdock shell $lxc -c nestat -ntulp
+    # test login pages
+    - lxdock shell $lxc -c curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"
+  
+  after_script:
+  - lxdock destroy -f
+
+UbuntuTrustyMysql:
+  stage: BackendDB_mysql
+  before_script:
+  # Create ansible.cfg with correct roles_path
+  - printf '[defaults]\nroles_path=../' > ansible.cfg
+
+  # Create .lxdock.yml
+  - |
+    echo """
+    name: $project
+
+    containers:
+      - name: $lxc
+        image: ubuntu/xenial
+        hostnames:
+          - $lxc
+
+    provisioning:
+      - type: ansible
+        playbook: tests/nextcloud10_mysql.yml
+    """ > .lxdock.yml
+  
+  script:
+    # Basic role syntax check
+    - ansible-playbook tests/nextcloud10_mysql.yml -i tests/inventory --syntax-check
+
+    # Deploy lxdock project and run the role/playbook
+    - lxdock up
+
+    # Run the role/playbook again, checking to make sure it's idempotent
+    - >
+      lxdock provision
+      | grep -q 'changed=0.*failed=0'
+      && (echo 'Idempotence test: pass' && exit 0)
+      || (echo 'Idempotence test: fail' && exit 1)
+
+    # Check for role is done
+    - lxdock shell $lxc -c nestat -ntulp
+    # test login pages
+    - lxdock shell $lxc -c curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"
+  
+  after_script:
+  - lxdock destroy -f
+
+UbuntuTrustyPsql:
+  stage: BackendDB_psql
+  before_script:
+  # Create ansible.cfg with correct roles_path
+  - printf '[defaults]\nroles_path=../' > ansible.cfg
+
+  # Create .lxdock.yml
+  - |
+    echo """
+    name: $project
+
+    containers:
+      - name: $lxc
+        image: ubuntu/xenial
+        hostnames:
+          - $lxc
+
+    provisioning:
+      - type: ansible
+        playbook: tests/nextcloud10_psql.yml
+    """ > .lxdock.yml
+  
+  script:
+    # Basic role syntax check
+    - ansible-playbook tests/nextcloud10_psql.yml -i tests/inventory --syntax-check
+
+    # Deploy lxdock project and run the role/playbook
+    - lxdock up
+
+    # Run the role/playbook again, checking to make sure it's idempotent
+    - >
+      lxdock provision
+      | grep -q 'changed=0.*failed=0'
+      && (echo 'Idempotence test: pass' && exit 0)
+      || (echo 'Idempotence test: fail' && exit 1)
+
+    # Check for role is done
+    - lxdock shell $lxc -c nestat -ntulp
+    # test login pages
+    - lxdock shell $lxc -c curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"
+  
+  after_script:
+  - lxdock destroy -f
+
+UbuntuTrusty:
+  stage: WebServer_Nginx
+  before_script:
+  # Create ansible.cfg with correct roles_path
+  - printf '[defaults]\nroles_path=../' > ansible.cfg
+
+  # Create .lxdock.yml
+  - |
+    echo """
+    name: $project
+
+    containers:
+      - name: $lxc
+        image: ubuntu/xenial
+        hostnames:
+          - $lxc
+
+    provisioning:
+      - type: ansible
+        playbook: tests/nextcloud10_nginx.yml
+    """ > .lxdock.yml
+  
+  script:
+    # Basic role syntax check
+    - ansible-playbook tests/nextcloud10_nginx.yml -i tests/inventory --syntax-check
+
+    # Deploy lxdock project and run the role/playbook
+    - lxdock up
+
+    # Run the role/playbook again, checking to make sure it's idempotent
+    - >
+      lxdock provision
+      | grep -q 'changed=0.*failed=0'
+      && (echo 'Idempotence test: pass' && exit 0)
+      || (echo 'Idempotence test: fail' && exit 1)
+
+    # Check for role is done
+    - lxdock shell $lxc -c nestat -ntulp
     # test login pages
     - lxdock shell $lxc -c curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"
   
